### ISSUE TITLE
Improve documentation in Transformer module

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#112]
**Description of feature/enhancement**
Current documentation in `../modules/transformer.py` is lacking. Could use better documentation. 

**Description of implementation**
See `../modules/scraper.py` for examples of documentation. Should be in following format:
```python
"""
Function description
----------
input : type
    description of input parameter
Returns
-------
output : type
    description of output parameter
"""
```

**Why this is a good feature/enhancement**
Better documentation would make it easier for first time contributors to jump right into code base.

**Additional context**
n/a

**Comment by Nahoyhp** [comment]
Hi, I am keen to taking this up.

I am wondering if I should write the documentation within the class / method, something similar to the image below since it seems to be the convention in Python.

![image](https://user-images.githubusercontent.com/54650877/102316440-e3963c80-3fb0-11eb-976a-bc7bccbaa526.png)

If you don't mind, I can do #113 as well. But if you want to leave it for other first timer, I am cool with it as well.



*FYI: The image is taken from [here](https://realpython.com/documenting-python-code/)

**Comment by Nahoyhp** [comment]
And can I add checks within the functions to be more defensive? 
Something like checking if the argument `text` is of type `String` and raising exception with message such as "Text passed into clean_text() in ../modules/transformer.py is not a String".

**Comment by skekre98** [comment]
Hi @Nahoyhp, I really appreciate you taking this up.  I just took a quick look at your PR and the convention you are following is perfect! It would be awesome if you could take a look at #113 as well 😄
